[package]
name = "the_salmon_river"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { version = "0.5.4", features = ["safeguards-dev-balanced"] }

[profile.dev]
debug = 2
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
debug = 0

[profile.fast]
inherits = "dev"
opt-level = 1
debug = 2

[profile.fast.package."*"]
opt-level = 3
debug = 0

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = "symbols"
