use godot::prelude::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, GodotConvert)]
#[godot(via = i64)]
pub enum SoundEffect {
    PlayerDeathBlow = 0,
    PlayerPunch = 1,
    PlayerKnockDown = 2,
    UIAccept = 3,
    UICancel = 4,
    UIDecrement = 5,
    UIIncrement = 6,
    PlayerPunchSwoosh = 7,
    PlayerPunchSwoosh1 = 8,
    PlayerFootStep = 9,
    WaterFootStep = 10,
    PlayerJump = 11,
    WingFlapDuck = 12,
    PlayerDuckQuack = 13,
    MatchStartSound = 14,
    ThrowLandPlayer = 15,
    PlayerGrab = 16,
    PlayerGotGrabbed = 17,
    ThrowableGrabbed = 18,
    CountdownTick = 19,
    MatchStartJingle = 20,
    MatchWinnerJingle = 21,
    MatchTieJingle = 22,
    IceChunkBreak = 23,
    LogBreak = 24,
    FishBreak = 25,
    LogAbility = 26,
    IceChunkAbility = 27,
    SalmonAbility = 28,
    StoneFootStep = 29,
}
impl SoundEffect {
    pub fn to_sound_effect_path(&self) -> &'static str {
        match self {
            SoundEffect::PlayerDeathBlow => "res://SoundAssets/death_blow.ogg",
            SoundEffect::PlayerPunch => "res://SoundAssets/punch.ogg",
            SoundEffect::PlayerKnockDown => "res://SoundAssets/knock_down.ogg",
            SoundEffect::UIAccept => "res://SoundAssets/ui_accept.ogg",
            SoundEffect::UICancel => "res://SoundAssets/ui_cancel.ogg",
            SoundEffect::UIDecrement => "res://SoundAssets/ui_decrement.ogg",
            SoundEffect::UIIncrement => "res://SoundAssets/ui_increment.ogg",
            SoundEffect::PlayerPunchSwoosh => "res://SoundAssets/swoosh.ogg",
            SoundEffect::PlayerPunchSwoosh1 => "res://SoundAssets/swoosh1.ogg",
            SoundEffect::PlayerFootStep => "res://SoundAssets/footstep.ogg",
            SoundEffect::WaterFootStep => "res://SoundAssets/splash_footstep.ogg",
            SoundEffect::PlayerJump => "res://SoundAssets/jump.ogg",
            SoundEffect::WingFlapDuck => "res://SoundAssets/wing_flap.ogg",
            SoundEffect::PlayerDuckQuack => "res://SoundAssets/quack.ogg",
            SoundEffect::MatchStartSound => "res://SoundAssets/match_start.ogg",
            SoundEffect::ThrowLandPlayer => "res://SoundAssets/throw_land.ogg",
            SoundEffect::PlayerGrab => "res://SoundAssets/player_grab.ogg",
            SoundEffect::PlayerGotGrabbed => "res://SoundAssets/player_got_grabbed.ogg",
            SoundEffect::ThrowableGrabbed => "res://SoundAssets/throwable_grabbed.ogg",
            SoundEffect::CountdownTick => "res://SoundAssets/countdown_tick.ogg",
            SoundEffect::MatchStartJingle => "res://SoundAssets/match_start_jingle.wav",
            SoundEffect::MatchWinnerJingle => "res://SoundAssets/winner_jingle.wav",
            SoundEffect::MatchTieJingle => "res://SoundAssets/tie_jingle.wav",
            SoundEffect::IceChunkBreak => "res://SoundAssets/ice_break.ogg",
            SoundEffect::LogBreak => "res://SoundAssets/log_break.ogg",
            SoundEffect::FishBreak => "res://SoundAssets/fish_break.ogg",
            SoundEffect::SalmonAbility => "res://SoundAssets/fish_use.ogg",
            SoundEffect::LogAbility => "res://SoundAssets/log_use.ogg",
            SoundEffect::IceChunkAbility => "res://SoundAssets/ice_chunk_use.ogg",
            SoundEffect::StoneFootStep => "res://SoundAssets/stone_footstep.ogg",
        }
    }
}
